### ISSUE TITLE
Highlight Keywords such as: "FLEXIBLE, option, object, record, null" in grammar

### ISSUE THREAD

**Issue by leefordjudes** [surrealdb/surrealql-grammar#6]
Highlight Keywords such as: 
1. FLEXIBLE, 
2. option, 
3. object, 
4. record, 
5. null
             in grammar
![image](https://github.com/surrealdb/surrealql-grammar/assets/13608248/835c1258-a930-4cf9-a9ba-9a8c4d55dc0f)

**Comment by kearfy** [comment]
Some of the more specific types will not be highlighted for the moment, as it will cause inconsistencies. We can highlight them down the road once an LSP is available however. Other issues are fixed now!
