### ISSUE TITLE
Highlight Keyword "FIELDS" in grammar while creating Index, but "COLUMNS" is already highlighted

### ISSUE THREAD

**Issue by leefordjudes** [surrealdb/surrealql-grammar#7]
![image](https://github.com/surrealdb/surrealql-grammar/assets/13608248/82e01871-4128-4868-acbd-361bed299328)

**Comment by kearfy** [comment]
Fixed by 7bea1a1f86b5f7f51c2f3fbbfa91bcb7867d78d8
